name: Nightly Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.tagname.outputs.tag_version }}
    steps:
      - name: Create version
        run: echo "tag_version=2.0.$(date +%s)" >> "$GITHUB_OUTPUT"
        id: tagname
      - name: Print version
        run: echo "created version ${{ steps.tagname.outputs.tag_version }}"
  nightly:
    needs: set_tag
    uses: Checkmarx/ast-jetbrains-plugin/.github/workflows/release.yml@main
    with:
      plugin: "both"
      ast_version: ${{ needs.set_tag.outputs.tag_version }}
      ignite_version: ${{ needs.set_tag.outputs.tag_version }}
      rchannels: "nightly"
    secrets: inherit
